### ISSUE TITLE
[Question] How can I set Topic configuration properties ?

### ISSUE THREAD

**Issue by majuansari** [jobcloud/php-kafka-lib#47]
Hi, Thanks for this brilliant package.

I have one question. How can I set Topic configuration properties? Say if I want to set _request.required.acks_ while creating my producer, how will I do that. Looking through the code, I found _RdKafka\TopicConf_ specified only for consumers. Or am I missing something here?

**Comment by nick-zh** [comment]
Thank you very much for the kind words.
As you can see here, default topic conf is deprecated: https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-conf.setdefaulttopicconf.html
Just set it directly on a global level
```
$conf->set('request.required.acks', '-1');
```
Stay safe and healthy
