### ISSUE TITLE
Undefined constant RD_KAFKA_RESP_ERR__FATAL

### ISSUE THREAD

**Issue by HergenD** [jobcloud/php-kafka-lib#52]
While trying to integrate this package in a laravel application I've ran in to two issues, **the first one** being the following error:

```bash
  ErrorException

  Use of undefined constant RD_KAFKA_RESP_ERR__FATAL - assumed 'RD_KAFKA_RESP_ERR__FATAL' (this will throw an Error in a future version of PHP)

  at vendor/jobcloud/php-kafka-lib/src/Callback/KafkaErrorCallback.php:26
     22▕      */
     23▕     public function __invoke($kafka, int $errorCode, string $reason)
     24▕     {
     25▕         // non fatal errors are retried by librdkafka
  ➜  26▕         if (RD_KAFKA_RESP_ERR__FATAL !== $errorCode) {
     27▕             return;
     28▕         }
     29▕
     30▕         throw new KafkaBrokerException(

      +1 vendor frames
  2   [internal]:0
      Jobcloud\Kafka\Callback\KafkaErrorCallback::__invoke()

      +17 vendor frames
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

I assumed this was due to my configuration but looking at the following stubs it seems like this constant does not exist
https://github.com/kwn/php-rdkafka-stubs/blob/master/stubs/constants.php

As far as I've been able to find this constant does exist in librdkafka 1.0.0+ while php-rdkafka supports 0.11+ (which is also what I have been running).

.

**The second issue** I ran in to is more of a question, and concerns the following error:
```bash
  ErrorException

  Undefined property: RdKafka\Message::$headers

  at vendor/jobcloud/php-kafka-lib/src/Consumer/AbstractKafkaConsumer.php:235
    231▕             (int) $message->offset,
    232▕             (int) $message->timestamp,
    233▕             $message->key,
    234▕             $message->payload,
  ➜ 235▕             (array) $message->headers
    236▕         );
    237▕     }
    238▕
    239▕     /**

      +17 vendor frames
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

I'm currently using confluent cloud and am able to set the message headers in the producer and also successfully view them in the confluent cloud panel. When trying to consume messages however, it seems like I'm not retrieving any headers at all, giving the error above. When I edit the  AbstractKafkaConsumer.php to check if headers exist before returning them it all works, although there will still not be any headers of course. 

If anyone has any idea what might cause this it'd be appreciated.

**Comment by Steveb-p** [comment]
Simple answer is - update librdkafka.

Unfortunately the package cannot really force the librdkafka version via composer constraints. What can be maybe done is more descriptive error message.

**Comment by HergenD** [comment]
Alright, I'll have to do that then. I guessed this would be the answer but since php-rdkafka supports 0.11 and debian/ubuntu only have support up to 0.11 through apt I was hoping there would be a simpler solution. 

It might be useful to note the minimum librdkafka version in the readme then too.

Thanks for the reply

**Comment by nick-zh** [comment]
Good point thx, i will add it shortly 👍

**Comment by HergenD** [comment]
Thanks nick. Would you happen to know what could be the issue with my second error (that one was not solved by the librdkafka version). If I dump the $rdKafkaMessage, all I get is the following:

```php
RdKafka\Message {#822
  +err: 0
  +topic_name: "users"
  +timestamp: 1611939124518
  +partition: 0
  +payload: "redacted"
  +len: 1709
  +key: "redacted"
  +offset: 29
  +opaque: null
  errstr: "Success"
}
```

So there are no headers present. This is using confluent cloud as mentioned, so the issue might lie there, but if that's the case, would it be possible to allow for headers not to be present?

**Comment by Steveb-p** [comment]
@HergenD that's also possibly due to low librdkafka version. Since phprdkafka calls librdkafka internally, any missing feature will influence how phprdkafka behaves. Missing headers might just be it.

**Comment by HergenD** [comment]
I should have mentioned it, but that second problem persist after building librdkafka 1.6

**Comment by Steveb-p** [comment]
@HergenD check if the runtime librdkafka used is the same as the one used for bulid.

You can see this in `phpinfo()` and `php -i`.

For example:

```shell
php -i | grep kafka
/usr/local/etc/php/conf.d/docker-php-ext-rdkafka.ini,
rdkafka
rdkafka support => enabled
librdkafka version (runtime) => 1.2.2
librdkafka version (build) => 1.2.2.255
```

**Comment by HergenD** [comment]
@Steveb-p 

```bash
/etc/php/7.4/cli/conf.d/20-rdkafka.ini,
rdkafka
rdkafka support => enabled
librdkafka version (runtime) => 1.6.0
librdkafka version (build) => 0.11.3.255
```

It is currently showing 2 different version.

**Edit:**

After successfully running it on an alpine image, it does indeed show the headers, so it seems like the problem was with the librdkafka version. Thanks for the help :)

**Comment by Steveb-p** [comment]
@HergenD pretty much yeah.

From what you've show the phprdkafka you were using was built against the librdkafka 0.11.3 headers. This meant that even when 1.6 librdkafka was used at runtime, the php wrapper seems to assume a limited feature set.

Basically what you needed to do is re-install (recompile) the phprdkafka to make it work.

**Comment by nick-zh** [comment]
We checked this and it seems the only problem is the error callback and that constant. Note will be added.
Thx for the report @HergenD and thx for helping out @Steveb-p :+1:
