### ISSUE TITLE
Use of undefined constant RD_KAFKA_OFFSET_BEGINNING - assumed 'RD_KAFKA_OFFSET_BEGINNING' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by odiejordie** [jobcloud/php-kafka-lib#58]
please help, when i try to integrate this library to lumen, i got this error while running crontab `php artisan schedule:run`
i'm using php 7,4 and using latest library for rdkafka

> php -i | grep kafka
> rdkafka
> rdkafka support => enabled
> librdkafka version (runtime) => 1.6.1
> librdkafka version (build) => 1.6.1.255

**Comment by Steveb-p** [comment]
@odiejordie Make sure that the php used in crontab matches the one in your user's CLI. Possibly your system has multiple php versions in it, and the one selected does not actually have phprdkafka extension.

In practice it's almost impossible to not have this constant defined for a proper installation of phprdkafka. It's one of the constants copied from librdkafka: https://github.com/arnaud-lb/php-rdkafka/blob/7ca71fe131eb230952ed5de5692647235fc85efc/rdkafka.c#L1033

**Comment by odiejordie** [comment]
thanks @Steveb-p
