### ISSUE TITLE
Produce failed with a fatal error. This producer instance cannot be used anymore.

### ISSUE THREAD

**Issue by adamkeesey** [jobcloud/php-kafka-lib#61]
Trying to use a transactional producer but keep getting this error:

Jobcloud\Kafka\Exception\KafkaProducerTransactionFatalException 
Produce failed with a fatal error. This producer instance cannot be used anymore.

I'm using the example in the README.

php: 8.0
rdkafka support => enabled
librdkafka version (runtime) => 1.4.2
librdkafka version (build) => 1.4.2.255
php-rdkafka: 5.0.0

From what I can tell, I met the requirements. Any advice would be great

**Comment by nick-zh** [comment]
You're transaction reached a fatal state. I saw that we are not exposing the original message, so right now it is hard to see what is going on, unless you add the below code [here](https://github.com/jobcloud/php-kafka-lib/blob/890efc85dc73d313e5e14330fbd8e600782753d3/src/Producer/KafkaProducer.php#L265)
```
var_dump($e->getMessage());
``` 
I'll get a fix out, so the original reason is exposed as well :v:

**Comment by nick-zh** [comment]
Sidenote: I advise updating to `librdkafka:1.7` as well, a lot of transaction related bugfixes have been included since `librdkafka:1.4`

**Comment by nick-zh** [comment]
I just created a [new release](https://github.com/jobcloud/php-kafka-lib/releases/tag/v1.5.0), the exception message should be more meaningful now, also with `$e->getPrevious()` you can get the original exception, i hope this helps you narrow the problem down. Let me know if you need additional help :v:

**Comment by adamkeesey** [comment]
Thank you, that extra error handling gave me "The Transactional API requires transactional.id to be configured". Just needed to add transactional.id on the producer configuration.

**Comment by nick-zh** [comment]
Cool, glad to hear it :v:
