### ISSUE TITLE
Not able to only decode messge body

### ISSUE THREAD

**Issue by varunkamra** [jobcloud/php-kafka-lib#68]
```
// if you are only decoding key or value, you can pass that mode as additional third argument
// per default both key and body will get decoded
$decoder = new AvroDecoder($registry, $recordSerializer /*, AvroDecoderInterface::DECODE_BODY */);
```

In the documentation it mentions that we can pass a third argument to tell the decoder to only decode the body, however the constant does not exist in AvroDecoderInterface. Is there another way to only decode the message body?

**Comment by varunkamra** [comment]
@nick-zh

**Comment by nick-zh** [comment]
sry about this confusion, this is not needed anymore. You can just not define a key schema anymore and it wont be encoded.
i advise against that though, some other kafka tools, might not play nice if you only encode key or value

**Comment by varunkamra** [comment]
Okay. The reason why I don't want to decode the key is because when the decoder tries to decode the key which is in uuid format it fails to decode correct schema id and in the next line it fails with exception Schema \<id\> not found.

https://github.com/flix-tech/avro-serde-php/blob/dc5de449e070c09f85a34d96ad336f1d0d9b4378/src/Objects/RecordSerializer.php#L134

Any ideas about this issue?

**Comment by nick-zh** [comment]
Could be one of the following reasons:
- schema was never registered in schema registry (maybe when you sent it locally or when you used a different SR locally)
- key schema was later deleted, so the message cannot be decoded anymore

It is very easy to check, you can look what the schema id is and check if it exists in your schema registry. If it doesn't something went wrong in between :v:
