### ISSUE TITLE
Deser AVRO not fetching new schema at runtime

### ISSUE THREAD

**Issue by raphaelauv** [jobcloud/php-kafka-lib#72]
**the avro consumer do not deser the data with the latest schema at runtime , but the latest schema seen at init of the cachedRegistry**

scenario : 

- publish a first schema for value and key 
- start the consumer 
- produce a message using first schema version of key and value
- publish a new version of the value schema
- produce a message using the new schema version of the value
- consumer decode the second message with the schema version 1 of value ( and not the v2 )

example if I only set the schema-registry

```php
$cachedRegistry = new CachedRegistry(
    new BlockingRegistry(
        new PromisingRegistry(
            new Client(
                [
                    'base_uri' => $this->parameterBag->get('kafka_schema_registry')
                ]
            )
        )
    ),
    new AvroObjectCacheAdapter()
);

$registry = new AvroSchemaRegistry($cachedRegistry);

$registry->addKeySchemaMappingForTopic(
    'external.domain-a.subdomain-b.access',
    new KafkaAvroSchema('external.domain-a.subdomain-b.access-key')
);
$registry->addBodySchemaMappingForTopic(
    'external.domain-a.subdomain-b.access',
    new KafkaAvroSchema('external.domain-a.subdomain-b.access-value')
);

$recordDeSerializer = new RecordSerializer($cachedRegistry);

new AvroDecoder($registry, $recordSerializer);
```

```
^ Jobcloud\Kafka\Message\KafkaConsumerMessage^ {#263
  #key: "de3a3f5"
  #body: array:5 [
    "event_timestamp" => 1654098320
    "event_datetime" => "2021-10-12T07:20:50.52Z"
    "event_id" => "8735875HDJDHSJ"
    "product_id" => 356
    "product_toto" => null
  ]
  #topicName: "external.domain-a.subdomain-b.access"
  #partition: 0
  #headers: []
  -offset: 8
  -timestamp: 1658312182639
}
```

but the real message is 
![Screenshot from 2022-07-20 12-39-22](https://user-images.githubusercontent.com/10202690/179962661-89658b70-b987-46e6-9a81-e2e392a9a302.png)

```

**Comment by nick-zh** [comment]
first of all i think there is a typo in your example, the proper way to register schemas for a topic is:
```
//if no version is defined, latest version will be used
//if no schema definition is defined, the appropriate version will be fetched form the registry
$registry->addBodySchemaMappingForTopic(
    'test-topic',
    new KafkaAvroSchema('bodySchemaName' /*, int $version, AvroSchema $definition */)
);
$registry->addKeySchemaMappingForTopic(
    'test-topic',
    new KafkaAvroSchema('keySchemaName' /*, int $version, AvroSchema $definition */)
);
```
As can be seen in the examples, you can omit the version to use latest
Without knowing how your schemas look like (versions for produce and consume) it is hard to give more feedback on this issue

**Comment by raphaelauv** [comment]
sorry I made the typo when I was creating the github issue ( removing the specific logic of my code )


`As can be seen in the examples, you can omit the version to use latest`

yes but the lib use latest at the init of the code, it do not fetch new versions of the schema at run time , is that correct ?

**Comment by nick-zh** [comment]
Correct

**Comment by nick-zh** [comment]
I need to elaborate more:
Yes since you are using `CachedRegistry` so it will fetch the schema once and cache it, if you don't want that you can probably just omit `CachedRegistry` then the schema should be fetcht on each decode, it will introduce a lot of latency though if you consume many messages

**Comment by raphaelauv** [comment]
yeah, thanks for your answer :+1: 

so the CachedRegistry is missing an option ( that should be true by default , cause it's the way confluent schema-registry java ser/deser lib work )

to deserialize messages using the schema that was use to serialize the message

**Comment by nick-zh** [comment]
That is not under our control, since the avro package is from [here](https://github.com/flix-tech/avro-serde-php)
They have a great team, i am sure they are open for improvements :v:

**Comment by raphaelauv** [comment]
I have open an issue there -> https://github.com/flix-tech/schema-registry-php-client/issues/69

It would be more correct to do it there -> https://github.com/flix-tech/avro-serde-php/issues ?

**Comment by nick-zh** [comment]
Probably on the serde side i guess :smile:
